### ISSUE TITLE
Clarify the difference from "envy" project

### ISSUE THREAD

**Issue by frol** [withoutboats/configure#6]
There is [envy](https://github.com/softprops/envy) project, which looks just like *configure* and I fail to find what makes these two different. Could you, please, compare them?

**Comment by withoutboats** [comment]
envy works as a possible configuration source. The default source in configure was partly inspired by envy.

But the value of configure is that libraries can be configured from the environment without depending on that configuration taking any form (e.g. it could be env vars, config files, or anything else), and guaranteeing that all libraries pull from the same source.

**Comment by frol** [comment]
I see it now! Thanks!
